[api]
api_key = something-stupid-over-here

[postgresql]
database    = kirigplants
host        = 10.172.50.240
user        = postgres
password    = your-secure-password
port        = 5432

[processing]
window_length = 128

[server]
host = 0.0.0.0
port = 8000