[api]
api_key = something-stupid-over-here

[postgresql]
dbname      = kirigplants
host        = 10.172.50.240
user        = postgres
password    = your-secure-password
port        = 5432

[processing]
window_length = 128
samples_per_second = 32

[server]
host = 10.42.0.1
port = 8000