[api]
api_key = something-stupid-over-here

[postgresql]
dbname      = kirigplants
host        = localhost
user        = FEJAY
password    = your-secure-password
port        = 5432

[processing]
window_length = 128
samples_per_second = 32

[server]
host = 0.0.0.0
port = 8000
